#!/usr/bin/env python3
"""Generate tools/pdfont.lua: a 1-bit bitmap font for the headless Playdate
renderer (tools/pdraster.lua), approximating the Playdate system font
metrics (line height 16, ~7px average advance, bold slightly wider).

Glyphs are rasterized once from Liberation Sans (13px, no antialiasing) and
stored as data, so pdraster itself has no font/Pillow dependency.
usage: python3 tools/genfont.py   (rewrites tools/pdfont.lua)
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONTDIR = "/usr/share/fonts/truetype/liberation/"
SIZE = 13
HEIGHT = 16
TRACKING = 1
# a few non-ASCII glyphs the Playdate system font also has (dashes, ellipsis,
# middle dot, curly quotes, common accents)
EXTRA = [0x2014, 0x2013, 0x2026, 0xB7, 0x2018, 0x2019, 0x201C, 0x201D, 0xE9, 0xF1, 0xFC, 0xB0]
VARIANTS = [("normal", "LiberationSans-Regular.ttf"),
            ("bold", "LiberationSans-Bold.ttf"),
            ("italic", "LiberationSans-Italic.ttf")]

out = ["-- GENERATED by tools/genfont.py -- do not edit by hand.",
       "-- 1-bit glyphs (ASCII 32-126 + a few extras, keyed by codepoint) for tools/pdraster.lua. Each glyph: advance,",
       "-- then one integer per row (bit (w-1-x) set = ink at column x), w = glyph width.",
       "return {", "  height = %d," % HEIGHT, "  variants = {"]
for name, fn in VARIANTS:
    font = ImageFont.truetype(FONTDIR + fn, SIZE)
    out.append("    %s = {" % name)
    for c in list(range(32, 127)) + EXTRA:
        ch = chr(c)
        g = Image.new("1", (32, HEIGHT), 1)
        d = ImageDraw.Draw(g)
        d.fontmode = "1"
        d.text((1, 0), ch, font=font, fill=0)
        adv = int(round(font.getlength(ch))) + TRACKING
        # glyph columns actually used (x offset 1 lets italics lean left)
        cols = [x for x in range(32) if any(g.getpixel((x, y)) == 0 for y in range(HEIGHT))]
        if cols:
            x0, x1 = min(cols), max(cols)
        else:
            x0, x1 = 1, 1
        w = x1 - x0 + 1
        rows = []
        for y in range(HEIGHT):
            v = 0
            for x in range(x0, x1 + 1):
                v = (v << 1) | (1 if g.getpixel((x, y)) == 0 else 0)
            rows.append(v)
        out.append("      [%d] = { a = %d, x = %d, w = %d, r = { %s } }," %
                   (c, adv, x0 - 1, w, ", ".join(str(v) for v in rows)))
    out.append("    },")
out.append("  },")
out.append("}")
with open(os.path.join(HERE, "pdfont.lua"), "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote pdfont.lua")
