#!/usr/bin/env python3
"""Pre-renders the web player's bitmap font atlas (font_data.js).

The Playdate draws its system font as 1-bit bitmaps; the web player does
the same from this atlas instead of anti-aliased canvas text. Glyphs are
rendered from Pixelify Sans (SIL Open Font License 1.1, by Stefie Justprince,
https://fonts.google.com/specimen/Pixelify+Sans) at 14px, regular and bold.

Usage: python3 make_font.py PixelifySans.ttf PixelifySansBold.ttf
"""
import sys, json
from PIL import Image, ImageDraw, ImageFont

HEIGHT, BASELINE, SIZE = 16, 12, 14

def atlas(path):
    font = ImageFont.truetype(path, SIZE)
    glyphs = {}
    for code in range(32, 127):
        ch = chr(code)
        adv = max(1, round(font.getlength(ch)))
        w = adv + 4
        img = Image.new("1", (w, HEIGHT), 0)
        d = ImageDraw.Draw(img)
        d.fontmode = "1"
        d.text((0, BASELINE), ch, font=font, fill=1, anchor="ls")
        rows = []
        for y in range(HEIGHT):
            bits = 0
            for x in range(w):
                if img.getpixel((x, y)):
                    bits |= 1 << x
            rows.append(bits)
        glyphs[code] = [adv, w, rows]
    return glyphs

out = {"height": HEIGHT, "fonts": [atlas(sys.argv[1]), atlas(sys.argv[2])]}
with open("font_data.js", "w") as f:
    f.write("// Generated by make_font.py from Pixelify Sans (SIL OFL 1.1). Do not edit.\n")
    f.write("window.CRANK_FONT = " + json.dumps(out, separators=(",", ":")) + ";\n")
print("wrote font_data.js")
