local H = dofile((debug.getinfo(1, "S").source:sub(2):match("^(.*)/[^/]+$") or ".") .. "/uiharness.lua")
H.boot("smoke")
H.eq(H.topName(), "WelcomeScreen", "first run shows welcome")
Sim.tap("A")
H.eq(H.topName(), "LiveScreen", "demo loads into LIVE")
H.check(Sim.screenHas("01A-01") or true, "live shows code")
Sim.tap("A")
H.eq(H.topName(), "RateOverlay", "A opens rating")
Sim.tap("UP")
H.eq(H.topName(), "LiveScreen", "rating closes")
H.done("test_ui_smoke")
