-- Screenshot tour of every screen (frames -> tools/render_frames.py).
-- usage: lua5.4 tests/tour.lua OUT_DIR
local H = dofile((debug.getinfo(1, "S").source:sub(2):match("^(.*)/[^/]+$") or ".") .. "/uiharness.lua")
H.frameDir = arg[1] or "/tmp/shotlist-frames"
os.execute('mkdir -p "' .. H.frameDir .. '"')
Sim.epoch = H.START_EPOCH + 3600 * 6 + 42 * 60 -- 12:37
H.boot("tour")
local function shot(name, expect)
	if expect then assert(H.topName() == expect, name .. ": expected " .. expect .. " got " .. H.topName()) end
	H.shoot(name)
end
shot("00-welcome", "WelcomeScreen")
Sim.tap("A")
for i = 1, 3 do Sim.tap("A"); Sim.tap(({ "DOWN", "RIGHT", "UP" })[i]); Sim.advance(90) end
Sim.hold("A", 600)
shot("01-live", "LiveScreen")
Sim.tap("A")
shot("02-rate", "RateOverlay")
Sim.hold("A", 600)
Sim.tap("LEFT")
shot("03-tech-issue", "IssuePicker")
Sim.tap("A"); Sim.wait(2)
Sim.crank(20, 2)
shot("04-live-scrub", "LiveScreen")
Sim.wait(1.5)
Sim.tap("B")
shot("05-details", "DetailsScreen")
Sim.tap("B"); Sim.tap("LEFT")
shot("06-status-picker", "PickerOverlay")
Sim.tap("B"); Sim.tap("RIGHT")
shot("07-gotit-next", "LiveScreen")
Sim.tap("UP")
shot("08-hub-undo-ready", "HubScreen")
Sim.tap("B"); Sim.wait(3)
Sim.tap("DOWN")
shot("09-slate", "SlateScreen")
Sim.tap("A")
shot("10-slate-logged", "SlateScreen")
Sim.tap("B")
H.hub("SHOT LIST")
shot("11-browser-shots", "BrowserScreen")
Sim.tap("B")
shot("12-browser-scenes", "BrowserScreen")
Sim.tap("RIGHT")
shot("13-scene-form", "FormScreen")
H.hub("NEW SHOT")
shot("14-builder", "BuilderScreen")
Sim.tap("DOWN"); Sim.crank(50, 4)
shot("15-builder-dial", "BuilderScreen")
Sim.tap("B")
shot("16-builder-confirm", "ConfirmOverlay")
Sim.tap("B")
H.hub("PROGRESS")
shot("17-progress", "ProgressScreen")
H.hub("CONTINUITY")
shot("18-continuity", "ContinuityScreen")
Sim.tap("A")
shot("19-cont-tag", "PickerOverlay")
Sim.tap("DOWN"); Sim.tap("A")
shot("20-keyboard")
Sim.type("MUG HALF FULL, HANDLE LEFT")
shot("21-cont-added", "ContinuityScreen")
H.hub("GEAR")
shot("22-gear", "GearScreen")
Sim.tap("DOWN"); Sim.tap("A")
shot("23-package", "FormScreen")
Sim.tap("DOWN"); Sim.tap("DOWN"); Sim.tap("A")
shot("24-multi", "MultiPickerOverlay")
H.hub("REPORT")
shot("25-report", "ReportScreen")
H.hub("PROJECT")
shot("26-project", "FormScreen")
H.hub("DATA")
shot("27-data", "FormScreen")
H.hub("SETTINGS")
shot("28-settings", "FormScreen")
App.home(); Sim.tap("B"); H.row("editsetup")
shot("29-setup-form", "FormScreen")
Sim.tap("A")
shot("30-enum-picker", "PickerOverlay")
Sim.tap("B")
-- flag card: go to another scene and come back to scene 1
App.home()
Sim.crank(400, 4); Sim.wait(1.5)
local sc = Model.ctx(App.cursorShot().id).scene.number
Sim.crank(-400, 4); Sim.wait(1.5)
shot("31-flag-panel", "LiveScreen")
Sim.tap("A")
local img = App.buildMenuImage()
local cmds = { { op = "clear", c = 1 }, { op = "image", x = 0, y = 0, s = 1, img = { w = 400, h = 240, bg = 1, cmds = img.cmds } } }
local f = io.open(H.frameDir .. "/32-menu-image.json", "wb"); f:write(json.encode({ cmds = cmds })); f:close()
print("frames: " .. H.shots .. " (scrub went to sc " .. sc .. ")")
