#!/usr/bin/env python3
"""Extracts every documented Playdate Lua API name from tools/playdate_api_stub.lua.

The stub is the community-maintained LuaCATS annotation file generated from
Panic's "Inside Playdate" documentation (github.com/notpeter/playdate-luacats).
We use it because the Playdate SDK cannot be installed in CI; the generated
list lets the headless tests and tools/check_api.py reject invented APIs.

Output: tests/pd_api.lua  (a Lua table of names)
"""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "tools/playdate_api_stub.lua").read_text()
funcs, methods, consts = set(), {}, set()
for m in re.finditer(r"^function ([\w\.]+)([:\.])(\w+)\(", src, re.M):
    owner, sep, name = m.groups()
    if sep == ".":
        funcs.add(owner + "." + name)
    else:
        methods.setdefault(owner, set()).add(name)
cls = None
for line in src.splitlines():
    mc = re.match(r"^---@class ([\w\.]+)", line)
    if mc:
        cls = mc.group(1)
        continue
    mf = re.match(r"^---@field (k\w+) ", line)
    if mf and cls:
        consts.add(cls + "." + mf.group(1))
out = ["-- GENERATED by tools/gen_api_list.py from tools/playdate_api_stub.lua. Do not edit.", "PD_API = {", "  functions = {"]
out += [f'    ["{f}"] = true,' for f in sorted(funcs)]
out += ["  },", "  methods = {"]
for owner in sorted(methods):
    out.append(f'    ["{owner}"] = {{ ' + ", ".join(f'"{n}"' for n in sorted(methods[owner])) + " },")
out += ["  },", "  constants = {"]
out += [f'    ["{c}"] = true,' for c in sorted(consts)]
out += ["  },", "}"]
(root / "tests/pd_api.lua").write_text("\n".join(out) + "\n")
print(len(funcs), "functions,", sum(len(v) for v in methods.values()), "methods,", len(consts), "constants")
