"""Technology tree.  cost is in research-points; era gates availability."""
from __future__ import annotations

FIELDS = ["agriculture", "materials", "energy", "computing", "ai", "biotech",
          "space", "weapons", "medicine", "social", "logistics", "finance"]

# name: (field, cost, prereqs, effects, blurb)
# Effects are free-form keys consumed by the relevant subsystem.
TECHS: dict[str, dict] = {
    # ---- agriculture ----
    "precision_ag":     dict(f="agriculture", c=900, p=[], e={"yield": 0.12, "fert_eff": 0.10},
                             d="Sensor-guided inputs; fewer tonnes of fertiliser for more tonnes of grain."),
    "drought_cultivars":dict(f="agriculture", c=1600, p=["precision_ag"], e={"yield": 0.10, "drought_res": 0.30},
                             d="Cultivars that shrug at a failed monsoon."),
    "vertical_farms":   dict(f="agriculture", c=3200, p=["precision_ag", "led_efficiency"],
                             e={"urban_food": 0.35, "land_need": -0.25},
                             d="Calories grown in towers, priced in kilowatts."),
    "cultured_protein": dict(f="agriculture", c=4800, p=["gene_editing"], e={"meat_cost": -0.40, "emissions": -0.06},
                             d="Meat without the animal, at last cheaper than the animal."),
    "nitrogen_fix":     dict(f="agriculture", c=5600, p=["catalysis", "gene_editing"],
                             e={"fert_need": -0.50, "yield": 0.08},
                             d="Cereals that fix their own nitrogen. Fertiliser markets never recover."),
    "aquaculture_3":    dict(f="agriculture", c=2100, p=["precision_ag"], e={"fish_yield": 0.35},
                             d="Closed-loop marine farming that does not strip the shelf."),
    # ---- materials ----
    "alloy_metallurgy": dict(f="materials", c=800, p=[], e={"unlock": "alloyworks", "quality": 0.08},
                             d="High-performance alloys for turbines, hulls, and barrels."),
    "composite_airframe":dict(f="materials", c=2400, p=["alloy_metallurgy"], e={"unlock": "aeroworks", "air_perf": 0.12},
                             d="Airframes that are lighter than the arguments about them."),
    "rare_separation":  dict(f="materials", c=1900, p=["catalysis"], e={"unlock": "mining_re"},
                             d="Solvent chemistry that pulls lanthanides apart economically."),
    "brine_extraction": dict(f="materials", c=1100, p=[], e={"unlock": "mining_li"},
                             d="Direct lithium extraction from brine at industrial scale."),
    "catalysis":        dict(f="materials", c=1200, p=[], e={"chem_eff": 0.15},
                             d="Catalysts that make hard reactions cheap."),
    "metamaterials":    dict(f="materials", c=6400, p=["nanofab"], e={"stealth": 0.25, "sensor": 0.15},
                             d="Structures that bend fields the way lenses bend light."),
    "nanofab":          dict(f="materials", c=5200, p=["euv_litho"], e={"quality": 0.15, "cost": -0.10},
                             d="Atom-scale assembly, still slow, no longer theoretical."),
    "superconductors":  dict(f="materials", c=8800, p=["metamaterials", "cryogenics"],
                             e={"grid_loss": -0.60, "unlock_fusion": 1},
                             d="Room-temperature superconduction. The grid stops leaking."),
    "carbon_capture":   dict(f="materials", c=4200, p=["catalysis"], e={"emissions": -0.18},
                             d="Direct air capture that finally beats its own energy bill."),
    "desalination_4":   dict(f="materials", c=2600, p=["catalysis"], e={"water": 0.40},
                             d="Membranes that make the sea drinkable at coal prices."),
    # ---- energy ----
    "pv_thinfilm":      dict(f="energy", c=1000, p=[], e={"unlock": "power_solar"},
                             d="Photovoltaics printed by the square kilometre."),
    "turbine_offshore": dict(f="energy", c=1300, p=["alloy_metallurgy"], e={"unlock": "power_wind"},
                             d="Floating turbines in water too deep to anchor."),
    "grid_storage":     dict(f="energy", c=2200, p=["pv_thinfilm"], e={"grid_stab": 0.30},
                             d="Storage that turns intermittent power into baseload."),
    "fission_gen3":     dict(f="energy", c=2600, p=["alloy_metallurgy"], e={"unlock": "power_nuclear"},
                             d="Passively safe reactors that regulators can be argued into."),
    "isotope_sep":      dict(f="energy", c=2900, p=["fission_gen3"], e={"unlock": "uranium_mine", "enrich": 1},
                             d="Centrifuge cascades. Also the first step to something else."),
    "breeder_cycle":    dict(f="energy", c=5400, p=["fission_gen3", "isotope_sep"], e={"fuel_eff": 0.50},
                             d="Reactors that make more fuel than they burn."),
    "cryogenics":       dict(f="energy", c=2300, p=[], e={"lng": 0.20},
                             d="Industrial cold, cheaply."),
    "fusion_ignition":  dict(f="energy", c=14000, p=["superconductors", "plasma_control"],
                             e={"unlock": "power_fusion", "prestige": 0.30},
                             d="Net-positive fusion. Everything downstream of energy price changes."),
    "plasma_control":   dict(f="energy", c=7200, p=["ml_scaling", "superconductors"], e={"fusion_step": 1},
                             d="Real-time magnetohydrodynamic control of a burning plasma."),
    "beamed_power":     dict(f="energy", c=9600, p=["orbital_lift", "metamaterials"], e={"orbital_power": 1},
                             d="Power from orbit, delivered as microwave rain."),
    # ---- computing ----
    "euv_litho":        dict(f="computing", c=3400, p=[], e={"unlock": "fabs"},
                             d="Extreme-ultraviolet lithography. Four companies on Earth can do it."),
    "hyperscale":       dict(f="computing", c=2000, p=[], e={"unlock": "datacenters"},
                             d="Datacentres measured in gigawatts, not racks."),
    "photonic_compute": dict(f="computing", c=7800, p=["euv_litho", "metamaterials"], e={"compute": 0.45},
                             d="Optical interconnect ends the memory wall."),
    "quantum_error":    dict(f="computing", c=9800, p=["cryogenics", "photonic_compute"], e={"crypto_break": 1},
                             d="Fault-tolerant qubits. Every archived secret becomes readable."),
    "post_quantum":     dict(f="computing", c=4600, p=["euv_litho"], e={"crypto_def": 1},
                             d="Lattice cryptography that survives the machines that break the rest."),
    "neuromorphic":     dict(f="computing", c=6600, p=["nanofab"], e={"compute": 0.25, "power_need": -0.35},
                             d="Chips that compute the way tissue does — badly, but for nothing."),
    "swarm_net":        dict(f="computing", c=3800, p=["hyperscale"], e={"c2": 0.20},
                             d="Mesh networking that survives the loss of any node."),
    # ---- ai ----
    "ml_scaling":       dict(f="ai", c=2800, p=["hyperscale"], e={"research": 0.15},
                             d="Scaling laws hold longer than anyone budgeted for."),
    "agentic_systems":  dict(f="ai", c=5200, p=["ml_scaling"], e={"admin_eff": 0.25, "unemployment": 0.05},
                             d="Software that pursues goals across weeks without supervision."),
    "world_models":     dict(f="ai", c=8400, p=["agentic_systems", "photonic_compute"],
                             e={"research": 0.30, "forecast": 0.35},
                             d="Models that simulate economies and armies well enough to bet on."),
    "autonomous_labs":  dict(f="ai", c=9200, p=["world_models", "robotics_dense"], e={"research": 0.45},
                             d="Closed-loop laboratories that run experiments while you sleep."),
    "recursive_design": dict(f="ai", c=16000, p=["autonomous_labs", "quantum_error"],
                             e={"research": 0.90, "singularity": 1, "risk": 0.35},
                             d="Systems that improve their own successors. The curve leaves the page."),
    "alignment_theory": dict(f="ai", c=6800, p=["world_models"], e={"risk": -0.45},
                             d="A real theory of control for systems smarter than their operators."),
    "synthetic_media":  dict(f="ai", c=3200, p=["ml_scaling"], e={"propaganda": 0.35, "trust": -0.20},
                             d="Perfect fabricated footage. Evidence stops meaning anything."),
    "predictive_police":dict(f="ai", c=4400, p=["agentic_systems"], e={"repress_eff": 0.30, "unrest": 0.08},
                             d="Arrests made before the crime, with the error bars kept classified."),
    # ---- biotech ----
    "gene_editing":     dict(f="biotech", c=2400, p=[], e={"med": 0.15, "yield": 0.06},
                             d="Cheap, precise edits to any genome you can sequence."),
    "mrna_platform":    dict(f="biotech", c=2000, p=[], e={"vaccine_speed": 0.50},
                             d="Vaccine design in weeks rather than years."),
    "synthetic_bio":    dict(f="biotech", c=5800, p=["gene_editing"], e={"chem_eff": 0.25, "biorisk": 0.30},
                             d="Organisms designed as factories. Dual-use to the core."),
    "longevity_1":      dict(f="biotech", c=7400, p=["gene_editing", "proteomics"], e={"lifespan": 6, "cost": 0.10},
                             d="Senolytics that add healthy years for those who can pay."),
    "proteomics":       dict(f="biotech", c=3000, p=["ml_scaling"], e={"med": 0.20},
                             d="Structure prediction closes the loop from sequence to drug."),
    "neural_interface": dict(f="biotech", c=8600, p=["neuromorphic", "proteomics"], e={"control": 0.20, "unrest": 0.10},
                             d="High-bandwidth interfaces. The applications are not all medical."),
    "bioremediation":   dict(f="biotech", c=3600, p=["synthetic_bio"], e={"pollution": -0.30},
                             d="Engineered organisms that eat the last century's mistakes."),
    # ---- space ----
    "orbital_lift":     dict(f="space", c=3600, p=["composite_airframe"], e={"unlock": "spaceworks", "launch": -0.50},
                             d="Fully reusable heavy lift. Orbit becomes a freight problem."),
    "orbital_manufact": dict(f="space", c=6800, p=["orbital_lift", "robotics_dense"], e={"quality": 0.10, "prestige": 0.15},
                             d="Vacuum and microgravity as industrial inputs."),
    "lunar_isru":       dict(f="space", c=9400, p=["orbital_manufact"], e={"prestige": 0.30, "rare_supply": 0.20},
                             d="Propellant and metal from regolith. The Moon stops being a cost centre."),
    "deep_sensors":     dict(f="space", c=4200, p=["orbital_lift", "swarm_net"], e={"intel": 0.30},
                             d="Persistent global overhead coverage at sub-metre resolution."),
    "asteroid_mining":  dict(f="space", c=13000, p=["lunar_isru", "autonomous_labs"], e={"metal_supply": 0.45, "prestige": 0.35},
                             d="The first captured body pays for the entire programme twice."),
    # ---- weapons ----
    "guided_muni":      dict(f="weapons", c=1400, p=[], e={"accuracy": 0.20},
                             d="Precision guidance as the default, not the exception."),
    "drone_swarm":      dict(f="weapons", c=3400, p=["swarm_net", "agentic_systems"], e={"attrition": 0.25, "cost": -0.30},
                             d="Attritable mass. Numbers become a technology again."),
    "hypersonics":      dict(f="weapons", c=6200, p=["composite_airframe", "guided_muni"], e={"first_strike": 0.30},
                             d="Manoeuvring reentry that current defences cannot solve."),
    "directed_energy":  dict(f="weapons", c=7600, p=["superconductors", "grid_storage"], e={"air_defence": 0.40},
                             d="Cost-per-shot measured in cents. Drone swarms get expensive again."),
    "fission_device":   dict(f="weapons", c=8200, p=["isotope_sep", "guided_muni"], e={"nuclear": 1},
                             d="A deliverable fission weapon. The strategic table is rewritten."),
    "thermonuclear":    dict(f="weapons", c=12500, p=["fission_device"], e={"nuclear": 2},
                             d="Staged devices. Yields no longer bounded by fissile mass."),
    "missile_defence":  dict(f="weapons", c=11000, p=["directed_energy", "deep_sensors"], e={"abm": 0.45},
                             d="Layered interception. Deterrence starts to wobble."),
    "cyber_arsenal":    dict(f="weapons", c=4800, p=["agentic_systems"], e={"cyber": 0.40},
                             d="Pre-positioned access in every grid that matters."),
    "autonomous_arms":  dict(f="weapons", c=8800, p=["drone_swarm", "world_models"], e={"attrition": 0.35, "risk": 0.20},
                             d="Weapons that select their own targets. Treaties lag by a decade."),
    "orbital_strike":   dict(f="weapons", c=15500, p=["orbital_manufact", "hypersonics"], e={"first_strike": 0.50},
                             d="Kinetic bombardment from orbit. No warning worth the name."),
    # ---- medicine ----
    "bioimaging":       dict(f="medicine", c=1800, p=[], e={"unlock": "medtechworks", "med": 0.10},
                             d="Imaging that catches disease a decade early."),
    "universal_vax":    dict(f="medicine", c=6400, p=["mrna_platform", "proteomics"], e={"epidemic_res": 0.45},
                             d="Broad-spectrum prophylaxis against whole viral families."),
    "regen_medicine":   dict(f="medicine", c=7800, p=["gene_editing", "bioimaging"], e={"lifespan": 4, "med": 0.25},
                             d="Grown organs on demand. Transplant waiting lists end."),
    "public_health_ai": dict(f="medicine", c=3200, p=["ml_scaling", "bioimaging"], e={"epidemic_res": 0.25},
                             d="Outbreak detection from sewage, pharmacy tills, and search logs."),
    # ---- social / governance ----
    "digital_id":       dict(f="social", c=1600, p=["hyperscale"], e={"tax_eff": 0.20, "surveil": 0.15},
                             d="One identity per citizen, cryptographically enforced."),
    "algorithmic_gov":  dict(f="social", c=4600, p=["agentic_systems", "digital_id"], e={"admin_eff": 0.30, "legit": -0.08},
                             d="Policy set by optimiser. Efficient, and nobody can appeal it."),
    "mass_deliberation":dict(f="social", c=3400, p=["digital_id"], e={"legit": 0.15, "unrest": -0.10},
                             d="Sortition assemblies with real statutory power."),
    "behavioural_nudge":dict(f="social", c=2600, p=["ml_scaling"], e={"policy_uptake": 0.25},
                             d="Choice architecture applied at national scale."),
    "social_credit":    dict(f="social", c=5200, p=["digital_id", "predictive_police"], e={"control": 0.35, "legit": -0.15},
                             d="Compliance priced into every transaction a citizen makes."),
    # ---- logistics ----
    "autonomous_freight":dict(f="logistics", c=3000, p=["agentic_systems"], e={"ship_cost": -0.30},
                             d="Crewless hulls and driverless corridors."),
    "robotics_dense":   dict(f="logistics", c=4000, p=["actuator_dense", "ml_scaling"], e={"labor_sub": 0.30},
                             d="Robots that work in spaces designed for people."),
    "actuator_dense":   dict(f="logistics", c=2200, p=["alloy_metallurgy"], e={"unlock": "roboworks"},
                             d="Power-dense actuators; machines that move like animals."),
    "cold_chain_global":dict(f="logistics", c=1900, p=["cryogenics"], e={"perish": -0.40},
                             d="Unbroken refrigeration from field to shelf, anywhere."),
    "modular_ports":    dict(f="logistics", c=2800, p=["autonomous_freight"], e={"throughput": 0.30},
                             d="Ports that reconfigure themselves for whatever arrives."),
    # ---- finance ----
    "led_efficiency":   dict(f="materials", c=700, p=[], e={"power_need": -0.10},
                             d="Lighting and displays at a fraction of the draw."),
    "cbdc":             dict(f="finance", c=2400, p=["digital_id"], e={"tax_eff": 0.25, "capital_control": 0.30},
                             d="Programmable sovereign money. Every transaction is policy."),
    "algo_markets":     dict(f="finance", c=3000, p=["ml_scaling"], e={"liquidity": 0.20, "volatility": 0.15},
                             d="Machine market-making: tighter spreads, fatter tails."),
    "settlement_mesh":  dict(f="finance", c=4400, p=["post_quantum", "cbdc"], e={"fx_cost": -0.50},
                             d="Cross-border settlement without a correspondent bank in sight."),
    "shadow_ledger":    dict(f="finance", c=5600, p=["post_quantum"], e={"launder": 0.40},
                             d="Provably private value transfer at institutional scale."),
    "risk_synthesis":   dict(f="finance", c=6200, p=["world_models", "algo_markets"], e={"crash_res": 0.25},
                             d="Systemic risk modelled well enough to trade against."),
}

for _k, _v in TECHS.items():
    _v.setdefault("e", {})

TECH_LIST = list(TECHS)

# Era gating: minimum world tech level (0..1) before a tech may be started.
def era_gate(cost: int) -> float:
    return min(0.92, cost / 20000.0)


RESEARCH_PROJECTS = {
    # Player-run megaprojects: (cost, prereq techs, blurb)
    "singularity_engine": dict(c=52000, p=["recursive_design", "fusion_ignition"],
                               d="A self-improving industrial intelligence with a physical economy beneath it."),
    "orbital_ring":       dict(c=64000, p=["orbital_manufact", "superconductors", "asteroid_mining"],
                               d="A structure that makes orbit a commute and makes you its landlord."),
    "panopticon":         dict(c=38000, p=["social_credit", "deep_sensors", "quantum_error"],
                               d="Total-information awareness over every network on the planet."),
    "eternal_program":    dict(c=44000, p=["longevity_1", "regen_medicine", "neural_interface"],
                               d="Indefinite lifespan for a controlled list of names, starting with yours."),
    "world_reserve":      dict(c=30000, p=["settlement_mesh", "cbdc", "risk_synthesis"],
                               d="A settlement layer every central bank is forced to clear through."),
    "doctrine_engine":    dict(c=34000, p=["synthetic_media", "behavioural_nudge", "world_models"],
                               d="Narrative production tuned per-person, per-day, at planetary scale."),
}
